[package]
name = "rserver"
version = "0.1.0"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]

[dependencies]
clap = {version = "2.31", features = ["yaml"]}
nix = "0.10.0"
hwloc = "0.5.0"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
env_logger = "*"
